apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-analytics-service
  template:
    metadata:
      labels:
        app: log-analytics-service
    spec:
      containers:
      - name: analytics-deployment
        image: claudia179/analytics-img:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: log-analytics-service
spec:
  selector:
    app: log-analytics-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
